apiVersion: v1
kind: Pod
metadata:
  name: pod-with-single-value-from-config-map
spec:
  containers:
    - name: busybox
      image: busybox
      command: ["sleep", "3600"]
      env:
        - name: VARIABLE_FROM_CONFIG_MAP
          valueFrom:
            configMapKeyRef:
              name: env-var-config
              key: env-var
              optional: true