apiVersion: v1
kind: Pod
metadata:
  name: pod-with-env-from-config-map
spec:
  containers:
    - name: busybox
      image: busybox
      command: ["sleep", "3600"]
      envFrom:
        - configMapRef:
            name: env-var-config
            optional: true