apiVersion: v1
kind: Pod
metadata:
  name: serviceaccount-pod
  namespace: rbac-test
spec:
  serviceAccountName: pod-list-serviceaccount
  containers:
    - name: kubectl-container
      image: bitnami/kubectl:latest
      command: [ "sleep", "3600" ]