apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: uthred-pod-reader
  namespace: rbac-test
subjects:
  - kind: User
    name: uthred
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: pod-reader
  apiGroup: rbac.authorization.k8s.io