kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: my-two-node-cluster
nodes:
  - role: control-plane
    #needed for service access on WSL2
    #extraPortMappings: This tells Docker to map the container’s ports (NodePorts) to matching ports on your computer.
    #In this example, ports 30000, 31000, and 80 inside the cluster will be accessible on localhost:30000,
    #localhost:31000, and localhost:80 respectively.
    extraPortMappings:
      - containerPort: 30000
        hostPort: 30000
        protocol: TCP
      - containerPort: 31000
        hostPort: 31000
      - containerPort: 80
        hostPort: 80
        protocol: TCP
      - containerPort: 8080
        hostPort: 8080
        protocol: TCP
  - role: worker