kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: my-two-node-cluster
nodes:
  - role: control-plane
    #needed for service access on WSL2
    extraPortMappings:
      - containerPort: 30000
        hostPort: 30000
        protocol: TCP
  - role: worker