apiVersion: v1
kind: Service
metadata:
  name: busybox
  labels:
    app: busybox
spec:
  type: NodePort
  ports:
    - name: http
      port: 80
      targetPort: http

  # Note here that we match both the app and the version
  selector:
    app: busybox
    version: "1.36"