apiVersion: apps/v1
kind: Deployment
metadata:
  name: busybox-deployment-v1-36
  labels:
    app: busybox
spec:
  replicas: 3
  selector:
    matchLabels:
      app: busybox
      version: "1.36"
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: busybox
        version: "1.36"
    spec:
      containers:
        - name: busybox
          image: busybox:1.36
          command: ["sh", "-c", "while true; do echo Hello from BusyBox 1.36; sleep 10; done"]
          resources:
            limits:
              memory: "64Mi"
              cpu: "250m"