apiVersion: v1
kind: Service
metadata:
  name: busybox-headless
  labels:
    app: busybox
spec:
  clusterIP: None  # Headless service
  selector:
    app: busybox
  ports:
    - name: dummy
      port: 80
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: busybox
spec:
  #the name of the headless service
  serviceName: "busybox-headless"
  replicas: 3
  selector:
    matchLabels:
      app: busybox
  template:
    metadata:
      labels:
        app: busybox
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - name: busybox
          image: busybox:1.36
          command:
            - sh
            - -c
            - |
              echo "Starting pod $(hostname)..."; \
              while true; do sleep 3600; done
          volumeMounts:
            #each pod will have its own PVC
            - name: data
              mountPath: /data
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 256Mi
