apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment-v1
spec:
  replicas: 4
  selector:
    matchLabels:
      app: backend
      version: v1
  template:
    metadata:
      labels:
        app: backend
        version: v1
    spec:
      containers:
        - name: backend
          image: ghcr.io/learnk8s/jobs-api
          ports:
            - containerPort: 3000
